import './globals.css'

import Header from "@/app/components/Header";

import { Mulish } from 'next/font/google';
import Footer from "@/app/components/Footer";

const mulish = Mulish({
    weight: '400',
    subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
      <Header/>{children}
      {/* eslint-disable-next-line react/jsx-no-undef */}
<Footer/>
</body>
    </html>
  )
}
